{% set name = "compas_libigl" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6e87f7e2530459f813b6efb617ebd4ca031f6d000f4c5330ca1a9871bcc9641d

build:
  number: 1
  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}  # [win]
    - {{ PYTHON }} -m pip install . -v

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  host:
    - pip
    - python
    - nanobind >=1.3.2
    - scikit-build-core[pyproject] >=0.10
  run:
    - python
    - compas
    - numpy

test:
  imports:
    - compas_libigl
  requires:
    - pytest

about:
  home: https://github.com/compas-dev/{{ name }}
  license: MPL-2.0
  license_file:
    - LICENSE
    - LICENSE.igl
  summary: 'COMPAS friendly wrappers for libigl functions.'
  dev_url: https://github.com/compas-dev/{{ name }}
  doc_url: https://github.com/compas-dev/{{ name }}

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
    - petrasvestartas
